"""field added to students table;

Revision ID: c82d68994c97
Revises: 8c3d88b9b248
Create Date: 2026-09-21 20:32:56.910525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82d68994c97'
down_revision: Union[str, Sequence[str], None] = '8c3d88b9b248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('branch', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'branch')
    # ### end Alembic commands ###
