"""added resume to students

Revision ID: d0994e39df0b
Revises: c82d68994c97
Create Date: 2026-09-24 20:48:51.201229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0994e39df0b'
down_revision: Union[str, Sequence[str], None] = 'c82d68994c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('resume_path', sa.String(length=250), nullable=True))
    op.drop_column('students', 'branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('branch', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('students', 'resume_path')
    # ### end Alembic commands ###
